# All variables are in this file

# Screen variables
SCREEN_X    = 1200
SCREEN_Y    = 900
SCREEN_SIZE = (SCREEN_X, SCREEN_Y)
FPS         = 60

# Field variables
HORISONTAL  = 0
VERTICAL    = 1
DISTANCE_FROM_SCREEN = 50
FIELD_V = SCREEN_Y - 2* DISTANCE_FROM_SCREEN
FIELD_H = SCREEN_X - 2* DISTANCE_FROM_SCREEN
HORISONTAL_TO_GOAL = 160
PENTALTY_HORISONTAL = 160
PENTALTY_VERTICAL = 400
GOAL = 80
GOAL_H = 20

# Player Variables
PLAYER_RADIUS = 7
PLAYER_SPEED = 2
PLAYER_MAXSPEED = 2

# Boid variables
BOID_RADIUS     = 7
NUMBER_OF_BOIDS = 20
BOID_MAXSPEED   = 2
BOID_DISTANCE   = 25
VIEW_DISTANCE   = 85
BOID_SENTER     = 100
BOID_AVGSPEED   = 8

# Hoik variables
HOIK_RADIUS     = 10
NUMBER_OF_HOIKS = 2
HOIK_MAXSPEED   = 10

HOIK_DISTANCE       = 200
HOIK_VIEW_DISTANCE  = 100
HOIK_SENTER         = 100
HOIK_AVGSPEED       =  10

# Obstacle variables
OBSTACLE_RADIUS     = 20
NUMBER_OF_OBSTACLES = 3
OBSTACLE_DISTANCE   = 50