# All variables are in this file

# Screen variables
SCREEN_X    = 1200
SCREEN_Y    = 900
SCREEN_SIZE = (SCREEN_X, SCREEN_Y)
FPS         = 60

# Field variables
HORISONTAL  = 0
VERTICAL    = 1
DISTANCE_FROM_SCREEN = 50
FIELD_V = SCREEN_Y - 2* DISTANCE_FROM_SCREEN
FIELD_H = SCREEN_X - 2* DISTANCE_FROM_SCREEN
HORISONTAL_TO_GOAL = 160
PENTALTY_HORISONTAL = 160
PENTALTY_VERTICAL = 400
GOAL = 80
GOAL_H = 20

# Player Variables
PLAYER_RADIUS = 7
PLAYER_SPEED = 2
PLAYER_MAXSPEED = 2

BALL_MAXSPEED = 100